### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by hurry989** [HC133/Pummel#1]
Hello, can this pass the cloudflare test?

**Comment by HC133** [comment]
It can only bypass CF(default)

**Comment by hurry989** [comment]
How many connections can he attack

**Comment by HC133** [comment]
> How many connections can he attack

this Pummel can only send about 1.3k ops
I have another Pummel version that can send over 2k pps

**Comment by hurry989** [comment]
How can I contact you?Telegram？

**Comment by HC133** [comment]
> How can I contact you?Telegram？

I will not make my Tg known to public
But you can contact me by Discord HC#3341
If you need my Tg I will pm you in discord

**Comment by hurry989** [comment]
OK
